### ISSUE TITLE
Code in tweet text sometimes not formatted correctly

### ISSUE THREAD

**Issue by Beliavsky** [zmoon/FortranTipBrowser#4]
At https://zmoon.github.io/FortranTipBrowser/tips/097.html

it says

`use, intrinsic :: iso_fortran_env intrinsic :: sin`

which should appear on two lines.

**Comment by zmoon** [comment]
Thanks @Beliavsky. In #3 I changed my workflow so that I am pulling from Twitter and your readme using some scripts to create "draft" tips, which I then later edit. But in the editing I am still far behind, and my draft script is not (currently) smart enough to detect whether something in the tweet text is code.

**Comment by zmoon** [comment]
Now ones that haven't been formatted yet are at least identified. Someday I'll catch up...
